version: '3.7'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - NODE_ENV=development
    volumes:
      - type: bind
        source: .
        target: /usr/src/time_clock
      - /usr/src/app/node_modules
    depends_on:
    - pg
    tty: true
    stdin_open: true
  pg:
    image: postgres:12.0
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
volumes:
  pgdata:
